# Generated by Django 5.1.3 on 2024-12-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactfeedback',
            options={},
        ),
        migrations.AlterField(
            model_name='contactfeedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactfeedback',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactfeedback',
            name='subject',
            field=models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Feedback', 'Feedback'), ('Bug Report', 'Bug Report'), ('Feature Request', 'Feature Request')], max_length=50),
        ),
    ]
